---
- name: Prep Nodes
  hosts: cluster
  become: true
  become_method: ansible.builtin.sudo
  roles: [foundation]
- name: Initialize Primary Control Plane
  hosts: control_plane[0]
  roles: [init_master, post_master]
- name: Join Additional Control Planes and Workers
  hosts: control_plane:workers:!control_plane[0]
  become: true
  become_method: ansible.builtin.sudo
  roles: [init_node, post_node]
