---
- name: Generate a token for joining worker nodes
  ansible.builtin.command:
    cmd: kubeadm token create --print-join-command
  register: post_master_kube_join_command
  run_once: true
  changed_when: false
  delegate_to: "{{ groups['control_plane'][0] }}"
- name: Store the worker join command
  ansible.builtin.set_fact:
    post_master_join_command: '{{ post_master_kube_join_command.stdout }}'
  delegate_to: '{{ item }}'
  delegate_facts: true
  loop: "{{ groups['cluster'] }}"
  run_once: true
- name: Generate certificate key for control plane join
  ansible.builtin.command:
    cmd: kubeadm init phase upload-certs --upload-certs
  register: post_master_certificate_key_output
  run_once: true
  changed_when: false
  delegate_to: "{{ groups['control_plane'][0] }}"
  when:
    - control_plane_endpoint | length > 0
    - groups['control_plane'] | length > 1
- name: Extract certificate key
  ansible.builtin.set_fact:
    post_master_certificate_key: '{{ post_master_certificate_key_output.stdout_lines[-1] }}'
  run_once: true
  when:
    - control_plane_endpoint | length > 0
    - groups['control_plane'] | length > 1
    - post_master_certificate_key_output is defined
- name: Store the control plane join command
  ansible.builtin.set_fact:
    post_master_join_command_control_plane: '{{ post_master_kube_join_command.stdout }} --control-plane
      --certificate-key {{ post_master_certificate_key }}'
  delegate_to: '{{ item }}'
  delegate_facts: true
  loop: "{{ groups['cluster'] }}"
  run_once: true
  when:
    - control_plane_endpoint | length > 0
    - groups['control_plane'] | length > 1
    - post_master_certificate_key is defined
