---
- name: Generate kubeconfig for Kubernetes cluster
  ansible.builtin.command:
    cmd: kubectl config view --raw --minify --flatten
  register: kubeconfig_output
  delegate_to: localhost
- name: Save kubeconfig to temporary file
  ansible.builtin.copy:
    content: '{{ kubeconfig_output.stdout }}'
    dest: /tmp/generated_kubeconfig
    mode: '0600'
- name: Merge kubeconfig with existing configuration
  ansible.builtin.block:
    - name: Check if existing kubeconfig file exists
      stat:
        path: ~/.kube/config
      register: kubeconfig_stat
    - name: Merge kubeconfig if existing config is present
      ansible.builtin.command:
        cmd: |
          KUBECONFIG=/tmp/generated_kubeconfig:~/.kube/config
          kubectl config view --merge --flatten > ~/.kube/config
      when: kubeconfig_stat.stat.exists
      delegate_to: localhost
    - name: Move generated kubeconfig if no existing config
      ansible.builtin.command:
        cmd: mv /tmp/generated_kubeconfig ~/.kube/config
      when: not kubeconfig_stat.stat.exists
      ansible.builtin.delegate_to: localhost
- name: Clean up temporary files
  ansible.builtin.file:
    path: /tmp/generated_kubeconfig
    state: absent
  delegate_to: localhost
