---
- name: Check if cluster is already initialized
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: init_master_kubeadm_already_initialized
- name: Check if this node is already in a cluster
  ansible.builtin.command:
    cmd: kubectl get nodes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: init_master_existing_nodes
  failed_when: false
  changed_when: false
  when: init_master_kubeadm_already_initialized.stat.exists
- name: Set custom node name
  ansible.builtin.set_fact:
    init_master_kubelet_node_name: '{{ node_name | default(inventory_hostname) }}'
- name: Initialize the first Kubernetes Control Plane
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.command:
    cmd: >
      kubeadm init
      --pod-network-cidr={{ init_master_pod_network_cidr }}
      --node-name={{ init_master_kubelet_node_name }}
      {% if control_plane_endpoint %}--control-plane-endpoint={{ control_plane_endpoint }}
      --upload-certs{% endif %}
  when:
    - not init_master_kubeadm_already_initialized.stat.exists
    - inventory_hostname == groups['control_plane'][0]
  register: init_master_kubeadm_init_output
  changed_when: init_master_kubeadm_init_output.rc == 0
- name: Create .kube directory
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.file:
    path: /home/{{ init_master_kube_user }}/.kube
    state: directory
    owner: '{{ init_master_kube_user }}'
    group: '{{ init_master_kube_user }}'
    mode: '0755'
- name: Copy admin.conf to user's kube config
  become: true
  become_method: ansible.builtin.sudo
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ init_master_kube_user }}/.kube/config
    owner: '{{ init_master_kube_user }}'
    group: '{{ init_master_kube_user }}'
    mode: '0600'
    remote_src: true
- name: Install Flannel CNI
  ansible.builtin.include_tasks:
    file: install_flannel.yml
  when:
    - install_cni | bool
    - cni_plugin == "flannel"
    - inventory_hostname == groups['control_plane'][0]
- name: Install Calico CNI
  ansible.builtin.include_tasks:
    file: install_calico.yml
  when:
    - install_cni | bool
    - cni_plugin == "calico"
    - inventory_hostname == groups['control_plane'][0]
- name: Install Cilium CNI
  ansible.builtin.include_tasks:
    file: install_cilium.yml
  when:
    - install_cni | bool
    - cni_plugin == "cilium"
    - inventory_hostname == groups['control_plane'][0]
- name: Untaint Control Plane
  ansible.builtin.command:
    cmd: kubectl taint nodes --all  node-role.kubernetes.io/control-plane-
  environment:
    KUBECONFIG: /home/{{ init_master_kube_user }}/.kube/config
  failed_when: false
  changed_when: false
  when: inventory_hostname == groups['control_plane'][0]
- name: Apply node labels for control plane
  ansible.builtin.command:
    cmd: kubectl label node {{ init_master_kubelet_node_name }} {{ item.key }}={{ item.value
      }} --overwrite
  environment:
    KUBECONFIG: /home/{{ init_master_kube_user }}/.kube/config
  loop: '{{ (node_labels | default({})) | dict2items }}'
  when: [node_labels is defined, node_labels | length > 0]
  changed_when: false
  delegate_to: "{{ groups['control_plane'][0] }}"
